### ISSUE TITLE
Large variation in total score values

### ISSUE THREAD

**Issue by tttmika** [ELELAB/RosettaDDGPrediction#53]
Using cartesian_ref2015.yaml, I ran the energy calculation with 3 iterations and the flutter of values was very large (using Rosetta 3.12). The variation of the values was not that large when I calculated the same data set in 3 iterations. Here is the flag file of my calculation with Rosetta3.13 Which part is different?The structure used for input is the same.

-s dGT_0001.pdb
-ddg:mut_file 220803_mut_test # same syntax with what being used in ddg-monomer application.
-ddg:iterations 3 # can be flexible; 3 is fast and reasonable
-force_iterations true #If this flag is on the protocol will stop when the results converge on a score
-ddg::score_cutoff 1.0 #If the lowest energy scores are within this cutoff the protocol will end early.
-ddg::cartesian
-ddg::dump_pdbs false # you can save mutants pdb if you want
-ddg:bbnbrs 1 # bb dof, suggestion: i-1, i, i+1
-fa_max_dis 9.0 # modify fa_atr and fa_sol behavior, really important for protein stability (default: 6)  
-score:weights ref2015_cart

**Comment by elenapapaleo** [comment]
we also observed variabilities when we were using version 3.12 on some of the systems which sounded a bit suspicious then we recently switched to a more recent version of rosetta and the calculations seem to be more consistent. It seemed to us that the problem might have been fixed with release 2020.28 
From the commit logs of rosetta (in relation to cartesian_ddg)

commit 28f338acfb3bfd87048b38a04772486975dc83fa
Merge: f7f9ecb 75f0b8c
Date:   Thu Jul 2 13:04:25 2020 -0700
Merge pull request #4828 from RosettaCommons/dimaio/restrict_packing_in_cart_ddg
    Limit repacking in cartesian ddg from the 

Did you try with a more recent version of rosetta and are you still observing the same behavior? At the moment for our projects we are using rosetta/2022.11

**Comment by tttmika** [comment]
Thank you very much. I was also using Rosetta 3.12 at first, but when I tried using Rosetta 3.13, the values became very stable. I think it is probably the same phenomenon. Thank you very much. The values are very stable and I feel that I do not need to iterate.

**Comment by elenapapaleo** [comment]
Glad that it helped. I am closing the issue now
