### ISSUE TITLE
Scanning site saturation?

### ISSUE THREAD

**Issue by amardeepranu** [ELELAB/RosettaDDGPrediction#60]
Is there any way to run scanning site saturation (similar to MutateX) in an easy way without manually listing each residue position in the list file (I could manually do this with a small script but just wondering if there is a setting)? The reason I'm asking is that `rosetta_ddg_aggregate` gives the option to output mutatex compatible files for `ddg2heatmap` and others, however these tools throw an error since they can't find energy files for each residue position:

Error from ddg2heatmap because residue 1 wasn't included in the list file:

ERROR: Couldn't open energy file /home/ec2-user/proteins/optimization/rosetta/DNASE1_results/data/mutatex_compatible/MA1 or file in the wrong format

**Comment by ValeSora** [comment]
Hi!

Unfortunately, we do not have that feature implemented yet in the software, so you would need to manually generate a file (or use a custom script to do so) listing the positions you want to run the scan on.

However, this would be a very useful feature to add to RosettaDDGPrediction, and we will start working on it in the next weeks so that the generation of the positons' file for saturation scans can be automated.

Best regards,
Valentina

**Comment by elenapapaleo** [comment]
If I am understanding correctly what you need you can use this script get_poslist.py in the repository now. It will read in input the PDB file on which you want to perform the scan and generate the whole positional list. Then you combine it together with a mutlist with the 20 aa.
