### ISSUE TITLE
Error when running rosetta_ddg_run,

### ISSUE THREAD

**Issue by yongwang123222** [ELELAB/RosettaDDGPrediction#66]
Hello, when I run, these errors appear and I don’t know how to solve them. If you can help point out the solutions, I will be very grateful.

this is my run.sh:
_**Rosetta_ddg_run -p dsm_wt.pdb -cr /Users/wangyong/Desktop/wangyong_workshop/RosettaDDGPrediction/RosettaDDGPrediction/config_run/cartesian_ref2015.yaml -cs /Users/wangyong/Desktop/wangyong_workshop/RosettaDDGPrediction/RosettaDDGPrediction/config_settings/nompi.yaml -r $ROSETTA/ -l ./poslist.txt**_

_poslist.txt_ was obtained using get_poslist.py. I want to saturate mutate the entire sequence.

this is error when i run the run.sh
$ ./run.sh
_INFO:root:Now checking the configuration file /Users/wangyong/Desktop/wangyong_workshop/RosettaDDGPrediction/RosettaDDGPrediction/config_settings/nompi.yaml.
INFO:root:Now checking the configuration file /Users/wangyong/Desktop/wangyong_workshop/RosettaDDGPrediction/RosettaDDGPrediction/config_run/cartesian_ref2015.yaml.
ERROR:root:Could not generate the list of mutations: not enough values to unpack (expected 4, got 3)
Could not generate the list of mutations: not enough values to unpack (expected 4, got 3)_

**Comment by mtiberti** [comment]
hi @yongwang123222,

just a few notes about your command line:

- looks like you're trying to perform a complete scan with the cartesian protocol. Have you already performed the relax step as suggested in our guide, to prepare your structure for your actual calculation? Relax is performed using a command line like:
```
rosetta_ddg_run -p file.pdb  -cr relax2_ref2015.yaml -n 1 -r /usr/local/rosetta-2022.11/ -cs rosettampi.yaml
```

it generates a `relax` folder which contains the relaxed PDB file to use in the proper next steps
- regarding your command line, if you want to perform a saturation mutagenesis as I understand from your post, the easiest way to do so would be to provide a position list (as you're doing) and a list of residue types using `--reslistfile`, as well as the `--saturation` option. See our guide for the format of the reslist file ("Residue types list file"). The command line would look something like:
```
rosetta_ddg_run -p relax/my_relaxed_structure.pdb -cr cartesian_ref2015.yaml -n X -r $ROSETTA -cs rosettanompi.yaml -l position_list.txt --reslistfile my_residues_types.txt --saturation
```

- could you paste here an excerpt of your `poslist.txt`? I think that might be misformatted for some reason. Is it possible your PDB file doesn't have a defined chain name for one or more residues?

- you might also want to consider the more recent Cartesian2020 protocol instead of Cartesian - see references in our user guide

**Comment by yongwang123222** [comment]
Thank you very much for your reply. I thought there was no need to set residence_types_file. I am missing this item. Thank you for your help. Thank you sincerely. the problem has fixed.
